#每天需要投币的数量 [0,5]。
coin: 5
#送出即将过期礼物 [true,false]
gift: false
#银瓜子兑换为硬币 [true,false]
s2c: true
#月底自动使用B币卷 [{0,自己会使用},{1,给自己充电},{2,兑换成金瓜子}]
autoBiCoin: 1
#用户设备的标识 [android,ios]
platform: ios
#自定义优先给这些 up 的视频投币 , 以yml数组的形式 , 填写其 uid (mid)
## 591090683(千万烟火)、396599607（糖姨）、130763764（三太子）、5128788（青青）、390461123（徐大sao）
upList:
  - 5128788
  - 591090683
  - 396599607
  - 130763764
  - 390461123
#进行漫画签到任务 [true,false]
manga: true
#优先送出即将过期礼物给此up的直播间,填写其 uid
upLive:
#对于进行投币的视频选择是否点赞 , 默认不点赞 [0,1]
selectLike: 0
